const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.AdvancedRandom,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Exps.LayerName,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Sprite.Acts.SetZ,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Shape3D.Exps.Count,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.AdvancedRandom.Acts.CreatePermutationTable,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.AdvancedRandom.Exps.Permutation,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Sin.Exps.Value,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Shape3D.Exps.BBoxLeft,
		C3.Plugins.Shape3D.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Shape3D.Exps.BBoxTop,
		C3.Plugins.Shape3D.Exps.BBoxBottom,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.Shape3D.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.TiledBg.Acts.SetMeshSize,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetMeshPoint,
		C3.Plugins.System.Exps.time,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{Box: 0},
	{Mouse: 0},
	{Index: 0},
	{InitialX: 0},
	{InitialY: 0},
	{Tween: 0},
	{PuzzlePiece: 0},
	{Collider: 0},
	{NeighborChecker: 0},
	{Sine: 0},
	{GameManager: 0},
	{AdvancedRandom: 0},
	{Ground: 0},
	{WallLeft: 0},
	{WallDown: 0},
	{WallUp: 0},
	{WallRight: 0},
	{ListOfPuzzlePieces: 0},
	{Touch: 0},
	{Tutorial: 0},
	{Stone01: 0},
	{Stone03: 0},
	{Stone04: 0},
	{Stone02: 0},
	{Stone05: 0},
	{Water: 0},
	{TILESIZE: 0},
	{CameraAngle: 0},
	{AllowMovement: 0},
	{PositionX: 0},
	{PositionY: 0},
	{GRIDSIZE: 0},
	{SPEED: 0},
	{FREQUENCY: 0},
	{DISTORTION: 0},
	{Score: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	Box: class extends self.I3DShapeInstance {},
	Mouse: class extends self.IInstance {},
	PuzzlePiece: class extends self.I3DShapeInstance {},
	Collider: class extends self.ISpriteInstance {},
	NeighborChecker: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Ground: class extends self.ISpriteInstance {},
	WallLeft: class extends self.I3DShapeInstance {},
	WallDown: class extends self.I3DShapeInstance {},
	WallUp: class extends self.I3DShapeInstance {},
	WallRight: class extends self.I3DShapeInstance {},
	ListOfPuzzlePieces: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Tutorial: class extends self.ISpriteFontInstance {},
	Stone01: class extends self.I3DShapeInstance {},
	Stone03: class extends self.I3DShapeInstance {},
	Stone04: class extends self.I3DShapeInstance {},
	Stone02: class extends self.I3DShapeInstance {},
	Stone05: class extends self.I3DShapeInstance {},
	Water: class extends self.ITiledBackgroundInstance {}
}